### PR TITLE
Remove plone.app.jquerytools dependency.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@jaroel turns out we do not need p.a.jquerytools at all. Now we have failing tests for Plone 5.x though: https://github.com/plone/plone.app.workflowmanager/pull/60

Not sure if it is worth the effort to fix those issues. Could you try wfmanager on Plone 5.1 and get back to me?

**Comment by tisto** [comment]
@jaroel I did a quick check with Plone 4.3/5.0/5.1 and the wfmanager works AFAIK. I'd say we merge this one and then do another 1.1.x release.

**Comment by jaroel** [comment]
@tisto correct, it almost works!
Because p.a.jquerytools is disabled we no longer have overlays, which lead to broken links.
There's also some issues with cancel buttons that won't close overlays.
Locally I do have a working install with p.a.jquerytools :)

All in all it doesn't look like a lot of work either way.

**Comment by tisto** [comment]
@jaroel ok, then please look into that tomorrow...

**Comment by tisto** [comment]
Wrong approach. Closing.

**Pull request closed without merging**
